"""Testing comment

Revision ID: 979a4c4bbb74
Revises: 
Create Date: 2022-05-19 13:25:38.855436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979a4c4bbb74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('p_pid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('comment')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('studentnr', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('studentnr')
    )
    op.create_table('posts',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('Now()'), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('comments')
    # ### end Alembic commands ###
